const videoPath = "/assets/db/videos/30sek.mp4";
const countAll = 100;

export const db = [
  {
    "id": "1",
    "name": "Трон 3",
    "description": "Печально, дружище, печально" +
      "Печально, дружище, печально" +
      "Юрий Сенин 2" +
      "Печально, дружище, печально," +
      "Кончается мир как мираж. К тому ж, у тебя всё нормально," +
      "Не верь, это глупая блажь Мы точно живём по Завету," +
      "Роняя о каждом слезу?" +
      "Хватаю во сне сигарету," +
      "Проснувшись в холодном поту" +
      "Спасибо, дружище, спасибо," +
      "Что был в эти годы со мной," +
      "Сентябрь ухмыляется криво," +
      "Мол, все мы там будем, не ной",
    "imageURL": "/assets/db/imgs/1744216552-242951142.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 5,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "2",
    "name": "Конец",
    "description": "SecondTestDescription",
    "imageURL": "/assets/db/imgs/dracula.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 5,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "3",
    "name": "Трон 3",
    "description": "FirstTestDescription",
    "imageURL": "/assets/db/imgs/1744216552-242951142.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 5,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "4",
    "name": "Конец",
    "description": "SecondTestDescription",
    "imageURL": "/assets/db/imgs/dracula.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 5,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "5",
    "name": "Трон 3",
    "description": "FirstTestDescription",
    "imageURL": "/assets/db/imgs/1744216552-242951142.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 5,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "6",
    "name": "Конец",
    "description": "SecondTestDescription",
    "imageURL": "/assets/db/imgs/dracula.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 9,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "7",
    "name": "Трон 3",
    "description": "FirstTestDescription",
    "imageURL": "/assets/db/imgs/1744216552-242951142.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 8,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "8",
    "name": "Конец",
    "description": "SecondTestDescription",
    "imageURL": "/assets/db/imgs/dracula.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 8,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "9",
    "name": "Трон 3",
    "description": "FirstTestDescription",
    "imageURL": "/assets/db/imgs/1744216552-242951142.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 9,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
  {
    "id": "10",
    "name": "Конец",
    "description": "SecondTestDescription",
    "imageURL": "/assets/db/imgs/dracula.webp",
    "movieURL": videoPath,
    "year": 2020,
    "quality": "",
    "rating": 8,
    "genre": "Action",
    "actorsIDs": ["1", "2", "3", "4", "5"],
    "createdAt": "2020-01-01",
    "updatedAt": "2020-01-01",
    "countAll": countAll
  },
]

export const actorsDb = [
  {
    "id": "1",
    "surname": "Surname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "2",
    "surname": "FirstSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "3",
    "surname": "TestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "4",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "5",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "6",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "7",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "8",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "9",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "10",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "11",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "12",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
  {
    "id": "13",
    "surname": "FirstTestSurname",
    "name": "Test",
    "movieURL": "null",
    "age": "28",
    "birthday": "22.08.2000",
  },
]
